FTBFS with GCC 4.3: missing #includes
Package: turqstat
Version: 2.2.4-1
Usertags: ftbfs-gcc-4.3
Tags: patch

Your package fails to build with GCC 4.3.  Version 4.3 has not been
released yet but I'm building with a snapshot in order to find errors
and give people an advance warning.  In GCC 4.3, the C++ header
dependencies have been cleaned up.  The advantage of this is that
programs will compile faster.  The downside is that you actually
need to directly #include everything you use (but you really should
do this anyway, otherwise your program won't work with any compiler
other than GCC).  Some background of this can be found at
http://gcc.gnu.org/PR28080

You can reproduce this problem with gcc-snapshot (20070326-1 or higher)
from unstable. (Currently not available for i386, but for amd64, powerpc
and ia64.  I hope to have i386 binaries in the archive in ~3 weeks.)

> Automatic build of turqstat_2.2.4-1 on coconut0 by sbuild/ia64 0.49
...
> g++ -g -O2 -I. -Wall -c ./squishread.cpp
> ./squishread.cpp: In destructor 'virtual SquishRead::~SquishRead()':
> ./squishread.cpp:36: error: 'free' was not declared in this scope
> make[1]: *** [squishread.o] Error 1